<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Jim Carry</name>
   <tag></tag>
   <elementGuidId>7b3e4d8b-26b3-49bf-8f1e-c14c9a5a5b21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div[2]/div/div[16]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6ce67f34-e345-4117-a072-dd6888d02921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-card-head-title</value>
      <webElementGuid>b31ce8d0-cb95-40a3-bdf0-8449c928ce5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jim Carry</value>
      <webElementGuid>e7d31feb-74d7-4e88-8d73-33529a272d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-eCstlR bHvPVt&quot;]/div[@class=&quot;children&quot;]/div[@class=&quot;sc-jSgvzq bgeVEz&quot;]/div[@class=&quot;list&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-6&quot;]/div[@class=&quot;ant-card ant-card-bordered&quot;]/div[@class=&quot;ant-card-head&quot;]/div[@class=&quot;ant-card-head-wrapper&quot;]/div[@class=&quot;ant-card-head-title&quot;]</value>
      <webElementGuid>47821617-c35d-4a88-b2a2-18d3b96836f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[2]/div/div[16]/div/div/div/div</value>
      <webElementGuid>3f081925-05d8-49cc-95eb-fbfc7d85a77a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arnold Schwarzenegger'])[6]/following::div[6]</value>
      <webElementGuid>a68aedb9-0334-4334-991e-f60c040fe113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='John Travolta'])[1]/following::div[12]</value>
      <webElementGuid>277c544c-610f-4946-92a1-9e1c4e0d6696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm mới đơn đặt hàng'])[1]/preceding::div[5]</value>
      <webElementGuid>deb4e6ad-d2b1-4b74-b478-2a3194441efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Các sản phẩm đã được thêm'])[1]/preceding::div[7]</value>
      <webElementGuid>48ba0d3b-9721-4042-a4a0-185e420c2c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jim Carry']/parent::*</value>
      <webElementGuid>9d8f7b68-1abf-4920-98f4-5b27bfcc5969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/div/div</value>
      <webElementGuid>0b0fa28d-9e7b-4e58-a5ad-bc5495ea3739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Jim Carry' or . = 'Jim Carry')]</value>
      <webElementGuid>07819798-03ae-465e-ad28-cf3f38aa67b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
