<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_basic_username</name>
   <tag></tag>
   <elementGuidId>0bfb427c-2c09-4b7d-8520-50b566186cf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d937e72-12e5-4ce2-869f-461dc56a0bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_username</value>
      <webElementGuid>ac7bf2d1-767b-4f16-aa07-ec43d62cec70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>ca3e8545-aaba-4214-bd70-2c210ba061c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83bceab1-15f1-4087-b8fc-6df7df5ad35e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_username&quot;)</value>
      <webElementGuid>25330016-917f-4810-b4fd-a624f3bac183</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_username']</value>
      <webElementGuid>ea7b1312-4d30-4c8f-8c55-c77b8c40b876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div[2]/div/div/input</value>
      <webElementGuid>0ee18895-6e6a-417e-bb0c-2d5e682d874f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>52fc9f22-8c0a-4995-b3b6-873f8be1b26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'basic_username' and @type = 'text']</value>
      <webElementGuid>9396e914-a8f2-4a7c-bb26-d8b338ed5e0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
