<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_basic_password</name>
   <tag></tag>
   <elementGuidId>c29701ec-a37d-460f-8a59-a8757eee66dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea04a9f4-884e-45d7-b375-7fd985f6fd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>b26e4a0c-016d-49eb-9972-33d8f3107027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_password</value>
      <webElementGuid>a7cbe1c5-82b8-4e17-aaba-9fdbe861125e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4cb93335-c3db-4a96-b251-c8668a13d4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>689ee431-8047-401a-aa47-f37a29037b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>65661ad3-debd-490b-930c-d5bb0328fb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_password&quot;)</value>
      <webElementGuid>040d7671-2ef4-44b8-9d45-401191bbb02f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_password']</value>
      <webElementGuid>93a711e1-8a9e-4e82-8408-f57683811ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[2]/div[2]/div/div/span/input</value>
      <webElementGuid>9b5d2b9f-ea17-4314-844a-7019d22f022f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>b1f7f54c-b6c5-4217-a02a-a1b3810711a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'basic_password' and @type = 'password']</value>
      <webElementGuid>c8002257-ee6d-4abb-a70d-1b66000a240c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
